## 
## # Targets for running the examples in this REPRO.
## 

run-examples:           ## Run all of the examples.
	$(RUN_IN_REPRO) 'sleep 2 && make -C ${REPRO_EXAMPLES_DIR} all'

clean-examples:         ## Delete all products of examples.
	$(RUN_IN_REPRO) 'make -C ${REPRO_EXAMPLES_DIR} clean'
